// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: CC_proto/ChittyChat.proto

package CCBuffers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time []int32 `protobuf:"varint,1,rep,packed,name=time,proto3" json:"time,omitempty"`
	Id   int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Msg  string  `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CC_proto_ChittyChat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_CC_proto_ChittyChat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_CC_proto_ChittyChat_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetTime() []int32 {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Msg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Msg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Msg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ParticipantInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time []int32 `protobuf:"varint,1,rep,packed,name=time,proto3" json:"time,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CC_proto_ChittyChat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_CC_proto_ChittyChat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_CC_proto_ChittyChat_proto_rawDescGZIP(), []int{1}
}

func (x *ParticipantInfo) GetTime() []int32 {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ParticipantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ParticipantId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time []int32 `protobuf:"varint,1,rep,packed,name=time,proto3" json:"time,omitempty"`
	Id   int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ParticipantId) Reset() {
	*x = ParticipantId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CC_proto_ChittyChat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantId) ProtoMessage() {}

func (x *ParticipantId) ProtoReflect() protoreflect.Message {
	mi := &file_CC_proto_ChittyChat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantId.ProtoReflect.Descriptor instead.
func (*ParticipantId) Descriptor() ([]byte, []int) {
	return file_CC_proto_ChittyChat_proto_rawDescGZIP(), []int{2}
}

func (x *ParticipantId) GetTime() []int32 {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ParticipantId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_CC_proto_ChittyChat_proto protoreflect.FileDescriptor

var file_CC_proto_ChittyChat_proto_rawDesc = []byte{
	0x0a, 0x19, 0x43, 0x43, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x68, 0x69, 0x74, 0x74,
	0x79, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x43, 0x43, 0x42,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x39, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x33, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x32, 0xf6, 0x01, 0x0a, 0x0a, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x3e, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x43, 0x43,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x43, 0x43, 0x42, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e,
	0x43, 0x43, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x43, 0x43, 0x42, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x05, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x43, 0x43, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x12, 0x0e, 0x2e, 0x43, 0x43, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e,
	0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2f, 0x43, 0x43, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CC_proto_ChittyChat_proto_rawDescOnce sync.Once
	file_CC_proto_ChittyChat_proto_rawDescData = file_CC_proto_ChittyChat_proto_rawDesc
)

func file_CC_proto_ChittyChat_proto_rawDescGZIP() []byte {
	file_CC_proto_ChittyChat_proto_rawDescOnce.Do(func() {
		file_CC_proto_ChittyChat_proto_rawDescData = protoimpl.X.CompressGZIP(file_CC_proto_ChittyChat_proto_rawDescData)
	})
	return file_CC_proto_ChittyChat_proto_rawDescData
}

var file_CC_proto_ChittyChat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_CC_proto_ChittyChat_proto_goTypes = []interface{}{
	(*Msg)(nil),             // 0: CCBuffers.Msg
	(*ParticipantInfo)(nil), // 1: CCBuffers.ParticipantInfo
	(*ParticipantId)(nil),   // 2: CCBuffers.ParticipantId
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_CC_proto_ChittyChat_proto_depIdxs = []int32{
	1, // 0: CCBuffers.ChittyChat.Join:input_type -> CCBuffers.ParticipantInfo
	2, // 1: CCBuffers.ChittyChat.Stream:input_type -> CCBuffers.ParticipantId
	2, // 2: CCBuffers.ChittyChat.Leave:input_type -> CCBuffers.ParticipantId
	0, // 3: CCBuffers.ChittyChat.Publish:input_type -> CCBuffers.Msg
	2, // 4: CCBuffers.ChittyChat.Join:output_type -> CCBuffers.ParticipantId
	0, // 5: CCBuffers.ChittyChat.Stream:output_type -> CCBuffers.Msg
	3, // 6: CCBuffers.ChittyChat.Leave:output_type -> google.protobuf.Empty
	3, // 7: CCBuffers.ChittyChat.Publish:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CC_proto_ChittyChat_proto_init() }
func file_CC_proto_ChittyChat_proto_init() {
	if File_CC_proto_ChittyChat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CC_proto_ChittyChat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CC_proto_ChittyChat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CC_proto_ChittyChat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CC_proto_ChittyChat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CC_proto_ChittyChat_proto_goTypes,
		DependencyIndexes: file_CC_proto_ChittyChat_proto_depIdxs,
		MessageInfos:      file_CC_proto_ChittyChat_proto_msgTypes,
	}.Build()
	File_CC_proto_ChittyChat_proto = out.File
	file_CC_proto_ChittyChat_proto_rawDesc = nil
	file_CC_proto_ChittyChat_proto_goTypes = nil
	file_CC_proto_ChittyChat_proto_depIdxs = nil
}
